# Generated by Django 3.2.6 on 2021-08-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdata',
            options={'ordering': ['date'], 'verbose_name': 'Форма заявки', 'verbose_name_plural': 'Формы заявок'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['date_joined'], 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='formdata',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата заявки'),
        ),
    ]
