# Generated by Django 3.2.6 on 2021-08-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_person_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ready',
            name='mark',
        ),
        migrations.AddField(
            model_name='ready',
            name='mark01',
            field=models.BooleanField(default=0, verbose_name='Галочка готовности сбора информации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ready',
            name='mark02',
            field=models.BooleanField(default=0, verbose_name='Галочка готовности дизайна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ready',
            name='mark03',
            field=models.BooleanField(default=0, verbose_name='Галочка готовности разработки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ready',
            name='mark04',
            field=models.BooleanField(default=0, verbose_name='Галочка готовности тестирования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ready',
            name='mark05',
            field=models.BooleanField(default=0, verbose_name='Галочка готовности наполнения контентом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ready',
            name='mark06',
            field=models.BooleanField(default=0, verbose_name='Галочка готовности финального запуска'),
            preserve_default=False,
        ),
    ]
